apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  # Run two replicas to provide availability and keep
  # the API accessible if one pod fails
spec:
  replicas: 2

  selector:
    matchLabels:
      app: userapi

  template:
    metadata:
      labels:
        app: userapi

    spec:
      containers:
        - name: userapi
          image: userapi:1.1
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: DB_HOST
              value: postgres-service

            - name: DB_PORT
              value: "5432"

            - name: DB_USER
              value: userapi

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password

            - name: DB_NAME
              value: userapi

            - name: APP_PORT
              value: "8000"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: userapi-service
spec:
  selector:
    app: userapi

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080

  type: NodePort